// <auto-generated />
using System;
using ClothingStore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStore.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218121152_addUserInteraction")]
    partial class addUserInteraction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f81c19fd-26e6-4bf4-b0d5-9fe7b6ab964e",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@test.bg",
                            EmailConfirmed = true,
                            FirstName = "Martin",
                            LastName = "Grahovski",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.BG",
                            NormalizedUserName = "ADMIN@TEST.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAELsHLYJ3ohlX9t3pZfMqITIGBk0HCxoM7DgBvgJ4riXCt+YmwIuSdrY+Llv3lhURHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "YIXYIXE6GJSSN4KVYJROXMJQKQ2EVPJT",
                            TwoFactorEnabled = false,
                            UserName = "admin@test.bg"
                        });
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Everyday t-shirts in different fits, colors, and styles.",
                            IsActive = true,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warm and comfortable hoodies for casual wear and layering.",
                            IsActive = true,
                            Name = "Hoodies"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Denim jeans in slim, straight, and relaxed fits.",
                            IsActive = true,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Outerwear for all seasons: bombers, puffers, and more.",
                            IsActive = true,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sneakers and casual shoes for everyday comfort and style.",
                            IsActive = true,
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "white",
                            Hex = "#FFFFFF",
                            Name = "Бял"
                        },
                        new
                        {
                            Id = 2,
                            Code = "black",
                            Hex = "#000000",
                            Name = "Черен"
                        },
                        new
                        {
                            Id = 3,
                            Code = "gray",
                            Hex = "#808080",
                            Name = "Сив"
                        },
                        new
                        {
                            Id = 4,
                            Code = "navy",
                            Hex = "#001F3F",
                            Name = "Тъмносин"
                        },
                        new
                        {
                            Id = 5,
                            Code = "dark-blue",
                            Hex = "#00008B",
                            Name = "Тъмно син"
                        },
                        new
                        {
                            Id = 6,
                            Code = "light-blue",
                            Hex = "#ADD8E6",
                            Name = "Светло син"
                        },
                        new
                        {
                            Id = 7,
                            Code = "olive",
                            Hex = "#808000",
                            Name = "Маслинен"
                        },
                        new
                        {
                            Id = 8,
                            Code = "white-gray",
                            Hex = "#D3D3D3",
                            Name = "Бяло/сиво"
                        });
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "UrbanBasics",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft 100% cotton t-shirt with a regular fit. Easy to pair with jeans or shorts.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Classic Cotton T-Shirt",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "StreetLab",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oversized fit t-shirt with a minimal front print and bold back graphic.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Oversized Graphic Tee",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "NorthWear",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm fleece-lined hoodie with a kangaroo pocket and adjustable drawstrings.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Premium Hoodie",
                            Price = 59.90m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "NorthWear",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Everyday zip-up hoodie with soft interior, perfect for layering.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zip-Up Hoodie",
                            Price = 54.50m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "DenimCo",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit jeans with a comfortable stretch. Clean look for casual or smart outfits.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Slim Fit Jeans",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "DenimCo",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic straight fit denim with durable stitching and mid-rise waist.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Straight Fit Jeans",
                            Price = 74.00m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "AeroStyle",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light bomber jacket with a smooth finish and ribbed cuffs. Great for spring/fall.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lightweight Bomber Jacket",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "AeroStyle",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Insulated puffer jacket designed for cold days. Water-resistant outer layer.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Puffer Jacket",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "MoveX",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable lightweight sneakers with cushioned sole and breathable mesh upper.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Running Sneakers",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "MoveX",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimal leather sneakers for everyday wear. Clean look and durable outsole.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Casual Leather Sneakers",
                            Price = 119.00m
                        });
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 1,
                            IsActive = true,
                            ProductId = 1,
                            Size = "M",
                            Stock = 120
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 2,
                            IsActive = true,
                            ProductId = 2,
                            Size = "L",
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 3,
                            IsActive = true,
                            ProductId = 3,
                            Size = "M",
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 4,
                            IsActive = true,
                            ProductId = 4,
                            Size = "S",
                            Stock = 45
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 5,
                            IsActive = true,
                            ProductId = 5,
                            Size = "32",
                            Stock = 70
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 6,
                            IsActive = true,
                            ProductId = 6,
                            Size = "34",
                            Stock = 55
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 7,
                            IsActive = true,
                            ProductId = 7,
                            Size = "L",
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 2,
                            IsActive = true,
                            ProductId = 8,
                            Size = "M",
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            ColorId = 8,
                            IsActive = true,
                            ProductId = 9,
                            Size = "42",
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            ColorId = 1,
                            IsActive = true,
                            ProductId = 10,
                            Size = "43",
                            Stock = 35
                        });
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.UserInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Product", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.ProductVariant", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.UserInteraction", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClothingStore.Infrastructure.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ClothingStore.Infrastructure.Data.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
